### ISSUE TITLE
Send fbp discovery messages periodically

### ISSUE THREAD

**Issue by bergie** [c-base/mqttwebview#2]
Right now we're using a [foreign participant declaration](https://msgflo.org/docs/foreign/index.html) to make our "showurl" participants (provided by this software) to show up in [c-flo](https://github.com/c-base/c-flo):

https://github.com/c-base/c-flo/blob/master/participants/showurl.yml

It would be preferable for each mqttwebview instance to send these [discovery messages](https://msgflo.org/docs/communications/index.html) itself. This way we could remove these foreign participants from c-flo, and each new mqttwebview instance would appear automatically in the c-flo graph when it becomes online.

mqttwebview should send these messages to the `fbp` topic at start up, and periodically after that (every 60 seconds is a good default).

Here are examples of how these discovery messages look like:

```json
{
  "command": "participant",
  "protocol": "discovery",
  "payload": {
    "component": "c-base/farbgeber",
    "inports": [
      {
        "queue": "farbgeber.IN",
        "type": "bang",
        "id": "in"
      }
    ],
    "label": "Produce pleasing color palettes",
    "outports": [
      {
        "queue": "farbgeber.PALETTE",
        "type": "object",
        "id": "palette"
      }
    ],
    "role": "farbgeber",
    "id": "farbgeber92490",
    "icon": "tint"
  }
}
```

```json
{
  "command": "participant",
  "protocol": "discovery",
  "payload": {
    "component": "c-base/boardingurl",
    "inports": [
      {
        "queue": "boardingurl.IN",
        "type": "object",
        "id": "in"
      }
    ],
    "label": "Generate greeting URL for crew members that are boarding",
    "outports": [
      {
        "queue": "boardingurl.OUT",
        "type": "string",
        "id": "out"
      }
    ],
    "role": "boardingurl",
    "id": "boardingurl3406",
    "icon": "check"
  }
}
```

**Comment by bergie** [comment]
cc @coon42 would also be nice for https://github.com/c-base/farbgeber/tree/master/esp8266/mqtt_client

Example JSON:

```json
{
  "protocol": "discovery",
  "command": "participant",
  "payload": {
    "component": "c-base/panel",
    "label": "Color LED panel",
    "icon": "lightbulb-o",
    "inports": [
      {
        "queue": "panel/bubbler",
        "type": "object",
        "description": "Farbgeber-style palette to display",
        "id": "palette"
      }
    ],
    "outports": [],
    "role": "bubbler",
    "id": "bubbler"
  }
}
```

**Comment by uwekamper** [comment]
The auto-discovery mode now works for both the mqtt-webview-screens on HE1 and Siri.

I changed the graph as @bergie suggested to me and then restarted the c-flo and c-flo-foreign services. Then I noticed that the c-flo service did not start properly but instead kept failing with the following errors:
```
May 12 01:41:44 c-flo node[6216]: Skipping setup for participants without component available. Assuming already setup:
May 12 01:41:44 c-flo node[6216]:         ingress-data(ingress-table/data)
May 12 01:41:44 c-flo node[6216]:         ingress-lights(ingress-table/lights)
May 12 01:41:44 c-flo node[6216]:         he1(c-base/mqttwebview)
May 12 01:41:44 c-flo node[6216]:         weltenbaulab_panel(c-base/panel)
May 12 01:41:44 c-flo node[6216]: (node:6216) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 participant-added listeners added. Use emitter.setMaxListeners() to increase limit
May 12 01:41:45 c-flo node[6216]: participants togglelights
May 12 01:41:45 c-flo node[6216]: c-flo/togglelights_3r8fy(c-flo/togglelights) running on mqtt://10.0.1.17
May 12 01:41:45 c-flo node[6216]: participants boardingurl
May 12 01:41:45 c-flo node[6216]: boardingurl(c-flo/boardingurl) running on mqtt://10.0.1.17
May 12 01:41:45 c-flo node[6216]: participants farbgeber
May 12 01:41:45 c-flo node[6216]: farbgeber(c-flo/farbgeber) running on mqtt://10.0.1.17
May 12 01:41:45 c-flo node[6216]: participants NetworkBars
May 12 01:41:45 c-flo node[6216]: c-flo/NetworkBars_m9mm8(c-flo/NetworkBars) running on mqtt://10.0.1.17
May 12 01:41:48 c-flo node[6216]: Sent discovery message for weltenbaulab
May 12 01:41:48 c-flo node[6216]: --forever enabled
May 12 01:42:30 c-flo node[6216]: /opt/c-flo/node_modules/msgflo/src/msgflo.coffee:31
May 12 01:42:30 c-flo node[6216]:         throw err;
May 12 01:42:30 c-flo node[6216]:         ^
May 12 01:42:30 c-flo node[6216]: Error: Waiting for participant siri timed out
May 12 01:42:30 c-flo node[6216]:     at Timeout._onTimeout (/opt/c-flo/node_modules/msgflo/src/coordinator.coffee:74:21)
May 12 01:42:30 c-flo node[6216]:     at ontimeout (timers.js:380:14)
May 12 01:42:30 c-flo node[6216]:     at tryOnTimeout (timers.js:244:5)
May 12 01:42:30 c-flo node[6216]:     at Timer.listOnTimeout (timers.js:214:5)
May 12 01:42:30 c-flo systemd[1]: c-flo.service: Main process exited, code=exited, status=1/FAILURE
May 12 01:42:30 c-flo systemd[1]: c-flo.service: Unit entered failed state.
May 12 01:42:30 c-flo systemd[1]: c-flo.service: Failed with result 'exit-code'.
May 12 01:42:30 c-flo systemd[1]: c-flo.service: Service hold-off time over, scheduling restart.
May 12 01:42:30 c-flo systemd[1]: Stopped c-flo.service.
```
The reason for this behaviour was that the siri component was already in the graph, but I forgot to start the mqttwebview service on siri itself. That meant that there were no discovery messages in the `fbp` topic for the siri component. After starting mqttwebview on siri everything worked.

That makes me wonder: How does msgflo deal with components that are part of the graph but that are not properly discovered when msgflo starts executing the graph?

**Comment by bergie** [comment]
@uwekamper we can use `--ignore` for those. Though, I thought we had a `--ignore siri` in there?

https://github.com/c-base/c-flo/blob/master/systemd/c-flo.service#L3

cc/ @jonnor

**Comment by bergie** [comment]
cc/ @IGBC

also documented in https://github.com/c-base/c-flo#self-announcing-participants
